name: fluyzt
description: yzt powered  by flutter

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.4

  # State
  provider: ^6.0.2

  # Base Component
  # WebView iOS添加键值对 o.flutter.embedded_views_preview = YES
  webview_flutter: ^3.0.0
  device_info: ^2.0.3
  package_info: ^2.0.2
  quiver: ^3.0.1+1
  #  connectivity: ^0.4.3+6

  # Data
  #  json_annotation: ^2.4.0
  dio: ^4.0.4
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  shared_preferences: ^2.0.12
  # 本地json对象存储
  localstorage: ^4.0.0+1

  # Html Encoder/Decoder
  html_unescape: ^2.0.0
  # 解析html标签
  flutter_html: ^3.0.0-alpha.2

  # 判断list是否相等
  collection: ^1.15.0
  #  crypto: ^2.0.6

  # UI
  oktoast: ^3.1.5
  pull_to_refresh: ^2.0.0
#  flutter_swiper: ^1.1.6
  # 替代 flutter_swiper
  flutter_swiper_null_safety: ^1.0.2
#  cached_network_image: ^1.1.1
  cached_network_image: ^3.2.0
  # 类iOS侧滑菜单
  flutter_slidable: ^1.2.0
  # 谁用谁闪亮
  shimmer: ^2.0.0
  # 识别图片的主要颜色
#  palette_generator: ^0.2.0
  # 更新展示支持mark_down
  flutter_markdown: ^0.6.9
  flare_flutter: ^3.0.2

  # third_app
  # 启动第三方app
  url_launcher: ^6.0.18
  share: ^2.0.4 #分享
#  launch_review: ^3.0.1
  open_file: ^3.2.1

  # android权限弹窗
#  permission_handler: ^3.2.2

  # 上报 目前问题比较多
#  flutter_bugly: 0.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

#  build_runner: ^1.6.2
#  json_serializable: ^3.1.0

flutter:
  uses-material-design: true
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
    - family: kuaile # 站酷 快乐字体  https://fonts.google.com/?selection.family=Noto+Sans+SC&subset=chinese-simplified
      fonts:
        - asset: assets/fonts/ZCOOLKuaiLe-Regular.ttf
  assets:
    - assets/animations/
    - assets/images/
    - CHANGELOG.md

flutter_intl:
  enabled: true
